# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  lint:
    name: Revisión de código con Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Flake8
        run: pip install flake8

      - name: Ejecutar Flake8
        run: flake8 . --max-line-length=88 --exclude=./crawler/venv/,.c9/,./htmlprocessor/venv/,./scraper/venv/

  test:
    name: Pruebas Unitarias
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
  
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
  
      - name: Instalar dependencias
        run: pip install -r requirements.txt
  
      - name: Ejecutar pruebas unitarias
        run: pytest 

